@startuml
actor "CRM Manager" as User
participant "ConfigureProposalDocumentUI" as UI
participant "ConfigureProposalDocumentController" as Controller
participant "PersistenceContext" as Persistence
participant "RepositoryFactory" as Factory
participant "DocumentValidate" as Validator
participant "DocumentValidationPlugin" as Plugin
participant "ShowProposalRepository" as Repo
participant "ShowProposal" as Proposal

activate User

User -> UI : request template configuration
activate UI

UI -> Controller : configurableProposalList()
activate Controller

Controller -> Persistence : PersistenceContext()
activate Persistence

Persistence -> Factory : repositories()
deactivate Persistence

activate Factory
Factory -> Repo : proposals()
deactivate Factory

activate Repo
Repo -> Repo : findConfigurableProposals()
activate Repo
deactivate Repo

Repo --> Controller : list of proposals
deactivate Repo

Controller --> UI : proposals
deactivate Controller

UI -> User : show proposals and templates
User -> UI : select proposal and template
UI -> Controller: configureDocument(proposal, selectedTemplate, crmManager)

activate Controller

Controller -> Proposal: configureDocument(selectedTemplate, crmManager);
activate Proposal

Proposal -> Controller : documentContent
deactivate Proposal

Controller -> Validator : validate(documentContent)

activate Validator
Validator -> Plugin : validateDocument(documentContent)

activate Plugin
Plugin --> Validator : ValidationResult
deactivate Plugin

Validator --> Controller : ValidationResult
deactivate Validator

alt documentContent is valid
    Controller -> Controller : proposal.addDocument(documentContent)
    activate Controller
    deactivate Controller


    Controller -> Repo : save(proposal)
    activate Repo
    Repo --> Controller : confirmation
    deactivate Repo

    Controller --> UI : true
    UI --> User : show success message

else documentContent is invalid
    Controller -> UI : false
    deactivate Controller

    UI --> User : show validation errors
    deactivate UI
end

deactivate User
@enduml
