@startuml
'https://plantuml.com/sequence-diagram


  class Drone <<Entity>> <<root>>{
    }

    class SerialNumber <<Value Object>>{
    }

    enum DroneStatus <<Value Object>>{

        }

    'Drone -> x
    Drone --> "1" SerialNumber: serialNumber
    Drone --> "1" DroneStatus: status

@enduml