@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "DroneTech" as DT
participant ":CreateModelUI" as UI
participant ":CreateModelController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "modelRepository\n:ModelRepository" as MOD_REPO
participant "model\n:Model" as MODEL

activate DT

DT -> UI : requests to create a new drone model
activate UI
    UI --> DT : asks for model data(Serial Number)
        deactivate UI
    DT -> UI : submits data
    activate UI
    UI --> UI : keepData(serialNumber)
    UI --> DT : asks for confirmation
    deactivate UI
    DT -> UI : confirms data
    activate UI
    UI -> CTRL : addDrone(serialNumber)
    activate CTRL
        CTRL -> CTRL :getDroneRepository()
        activate CTRL
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getDroneRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : droneRepository
        deactivate REPOS_SINGLETON
        CTRL -->CTRL : droneRepository
        deactivate CTRL
            CTRL -> MOD_REPO : addDrone(serialNumber)
            activate MOD_REPO



        MOD_REPO -> MODEL : create(serialNumber)
        activate MODEL
        MODEL --> MOD_REPO : modelCreated
        deactivate MODEL
        MOD_REPO -> MOD_REPO: addModel (modelCreated)
                activate MOD_REPO
                    MOD_REPO -> MOD_REPO: validateModel(modelCreated)
                    activate MOD_REPO
                        MOD_REPO --> MOD_REPO : true
                    deactivate MOD_REPO

                    MOD_REPO --> MOD_REPO : true
                deactivate MOD_REPO
            MOD_REPO --> CTRL : true
        deactivate MOD_REPO

        CTRL --> UI : true
    deactivate CTRL

UI --> DT : displays success message
deactivate UI
deactivate DT

@enduml
