@startuml

package "Drone " <<aggregate>> {

    class Drone <<Entity>> <<root>>{
    }

    class SerialNumber <<Value Object>>{
    }

    enum DroneStatus <<Value Object>>{
    }

    class RemovalReason <<Value Object>>{
    }

    class DroneLanguage <<Value Object>>{
    }

    class DroneLanguageValidate <<Service>>{
    }

    'Drone -> x
    Drone --> "1" DroneStatus: status
    Drone --> "1" SerialNumber: serialNumber
    Drone --> "0..*" RemovalReason: removalReason
    Drone --> "1" DroneLanguage: language

    'DroneLanguageValidate -> x
    DroneLanguageValidate ..> "1" DroneLanguage: validates
}

package "ModelOfDrone " <<aggregate>> {

    class Model <<Entity>> <<root>>{
    }
    class ModelName <<Value Object>>{
    }
    class Configuration <<Entity>>{
    }

    class WindSpeed <<Value Object>>{
    }

    class PositionTolerance <<Value Object>>{
    }

    enum SafetyStatus <<Value Object>>{
    }

    'Model -> x
    Model --> "1" Configuration: configuration
    Configuration --> "1..*" WindSpeed: windSpeed
    Configuration --> "1..*" PositionTolerance: positionTolerance
    Model --> "1" ModelName: modelName
    Configuration --> SafetyStatus: safetyStatus


    'Drone -> x
    Drone --> "1" Model: uses

}

package "ShowProposal " <<aggregate>>{

    enum ShowProposalStatus <<Value Object>>{
    }

    class ShowProposal <<Entity>> <<root>>{
    }

    class ShowProposalDocument <<Value Object>>{
    }

    class ShowProposalNumber <<Value Object>>{
    }

    class Insurance <<Value Object>>{
    }

    class CustomerFeedback <<Value Object>>{
    }

    class ShowConfiguration <<Entity>>{
    }

    class ShowConfigurationFigure <<Value Object>>{
    }

    class Video <<Value Object>>{
    }

    class ProposalDocumentGenerator <<Service>> {
    }

    class ShowDSLDescription <<Value Object>> {
    }

    class GenerateShowDSL <<Service>> {
    }

    'ShowProposal -> x
    ShowProposal --> "1" CustomerFeedback: customerFeedback
    ShowProposal --> "1" CRMCollaborator: created by
    ShowProposal --> "1" CRMManager: template configured by
    ShowProposal --> "1" ShowRequest: based on
    ShowProposal --> "1" ShowProposalStatus: proposalStatus
    ShowProposal --> "1" ShowProposalDocument: document
    ShowProposal --> "1" ShowProposalNumber: proposalNumber
    ShowProposal --> "1" Insurance: insurance
    ShowProposal --> "1" ShowConfiguration: showConfiguration
    ShowProposal --> "1" Video: video

    'GenerateShowDSL -> x
    GenerateShowDSL ..> ShowConfiguration: uses
    GenerateShowDSL --> ShowDSLDescription: returns

    'ProposalDocumentGenerator -> x
    ProposalDocumentGenerator ..> "1" ShowProposalDocument: validates & generates

    'ShowConfiguration -> x
    ShowConfiguration --> "1..*" ShowConfigurationFigure: figures
        ShowConfiguration -> "0..1" ShowDSLDescription: showDSLDescription


    'ShowConfiguration -> x
    ShowConfiguration --> "1..*" Model: models

    ShowConfiguration -> "0..1" ShowDSLDescription: showDSLDescription

}

@enduml