@startuml
set separator none

package "Persistence " #DDDDDD {
    class PersistenceContext {
        + getRepositoryFactory(): RepositoryFactory
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaRepositoryFactory {
        - JpaRepositoryFactory()
        + getInstance(): RepositoryFactory
    }

    class JpaFigureRepository {
    }

}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryRepositoryFactory {
        - InMemoryRepositoryFactory()
        + getInstance(): RepositoryFactory
    }

    class InMemoryFigureRepository {
    }
}

package "Domain" #DDDDDD {

    package "Repository " #DDDDDD {

        interface RepositoryFactory {
            + getFigureRepository(): FigureRepository
        }

        interface FigureRepository {
            + getPublicCatalogue() : List<Figure>
        }

    }

    'Figure Aggregate
    class Figure <<Entity>>{
        + isPublic() : boolean
        + isActive() : boolean
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    'Category Aggregate
    class Category <<Entity>>{
    }

    class CategoryName <<Value Object>>{
    }

}

package "UI" #DDDDDD {
    class ListPublicCatalogueUI <<UI>> {
        + showPublicFigures()
    }
}

package "Controller" #DDDDDD {
    class ListPublicCatalogueController <<Controller>> {
        + listPublicCatalogue()
    }
}

'Persistence

    'PersistenceContext -> x
    PersistenceContext ..> RepositoryFactory: figureRepository()
    PersistenceContext ..> JpaRepositoryFactory
    PersistenceContext ..> InMemoryRepositoryFactory

'persistence.impl.jpa

    'JpaFigureRepository -> x
    JpaFigureRepository --|> FigureRepository

    'JpaRepositoryFactory -> x
    JpaRepositoryFactory ..|> RepositoryFactory
    JpaRepositoryFactory ..> JpaFigureRepository

'persistence.impl.inmemory

    'InMemoryFigureRepository -> x
    InMemoryFigureRepository ..|> FigureRepository

    'InMemoryRepositoryFactory -> x
    InMemoryRepositoryFactory ..|> RepositoryFactory
    InMemoryRepositoryFactory ..> InMemoryFigureRepository

'Repository

    'FigureRepository -> x
    FigureRepository ...> Figure

    'RepositoryFactory -> x
    RepositoryFactory ..> FigureRepository

'Domain

    'Figure -> x
    Figure --> "1..*" Keyword: keywords
    Figure --> "1" Code: code
    Figure --> "1" Version: version
    Figure --> "1" Description: description
    Figure --> "1..*" Category: categories

    'Category -> x
    Category --> "1" CategoryName: name

'UI

    'ListPublicCatalogueUI -> x
    ListPublicCatalogueUI ..> ListPublicCatalogueController

'Controller

    'ListPublicCatalogueController -> x
    ListPublicCatalogueController ..> PersistenceContext : getRepositoryFactory()
    ListPublicCatalogueController ..> RepositoryFactory : getFigureRepository()
    ListPublicCatalogueController ..> FigureRepository : getPublicCatalogue()


@enduml