@startuml

class BackOfficeOpt <<Entity>>{

}

class Client <<Entity>>{

}

class PublicEntity <<value object>>{
}

class Address <<value object>>{
    street
    number
    city
    country
    postal code
}

class EuropeanVatNumber <<value object>>{
}

class Library <<Entity>>{
}

class Drone <<Entity>>{
    routine
}

class Figures <<Entity>>{
    code
    description
    version
    clients
}

class CreativeDepartment <<Entity>>{
}

Enum ClientStatus <<value object>>{

}

note left of ClientStatus
  Deleted, Infringement,
  Created, Regular, Vip
end note

class User <<Entity>>{
}

class PhoneNumber <<value object>>{
}

class Name <<value object>>{
}

class Email <<value object>>{
}

class Admin <<Entity>>{
}

class CRMManager <<Entity>>{

}

class CRMCollaborator <<Entity>>{
}

class ShowDesigner <<Entity>>{
}

class DroneTech <<Entity>>{
}

class Representatives <<Entity>>{
    email
    name
    position
}

class Show <<Entity>>{
    description
}

Client --> EuropeanVatNumber
Client --> Address

Client --|> User
CRMCollaborator --|> User
CRMManager --|> User
Admin --|> User
ShowDesigner --|> User
DroneTech --|> User

User --> PhoneNumber
User --> Name
User --> Email

Client "1" --- "1.*" Representatives :> interact with
Client "1" --- "1" ClientStatus :> has


class ShowRequest {
    place
    time
    number of drones
    duration

}

class Proposal {

}

Client "1" --- "1" CRMCollaborator :> contacts to submmit
ShowRequest "1" --- "1" Client
ShowRequest "1" --- "1" Show : has
ShowRequest "1" --- "1" CRMCollaborator
CRMManager "1" --- "1" ShowDesigner
ShowDesigner "1" --- "1" ShowRequest
CRMCollaborator "1" --- "1" Proposal
CRMCollaborator "1" --- "1" Client

@enduml