@startuml

package "Customer " <<aggregate>> {
    class Customer <<Entity>> <<root>>{
    }

    class Representative <<Entity>>{
    }

    class Address <<Value Object>>{
    }

    class VatNumber <<Value Object>>{
    }

    enum CustomerStatus <<Value Object>>{
    }

    class Position <<Value Object>>{
    }

    'Customer -> x
    Customer  --> "1..*" Representative : represented by
    Customer --> "1" VatNumber : vat
    Customer --> "1" Address : address
    Customer --> "1" CustomerStatus : status

    'Representative -> x
    Representative --> "1" Position : position

}

package Shared {

    class Name <<Value Object>>{
    }

    class Email <<Value Object>>{
    }

    'Representative -> x
    Representative --> "1" Name : name
    Representative --> "1" Email : email

}


@enduml