@startuml

package "Figure " <<aggregate>> {

    class Figure <<Entity>> <<root>>{
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    class DSLDescription <<Value Object>>{
    }

    class Category <<Entity>>{
    }

    class idCategory <<Value Object>>{
    }

    class CategoryStatus <<Value Object>>{
    }

    class FigureStatus <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }

    class idExclusivity <<Value Object>>{
    }

    class DSLValidate <<Service>>{
    }


    'Figure -> x
    Figure --> "1" DSLDescription: DSLDescription
    Figure --> "1" Category: category
    Figure --> "1..*" Keyword: keywords
    Figure --> "1" Exclusivity: exclusivity
    Figure --> "1" Code: code
    Figure --> "1" Version: version
    Figure --> "1" Description: description
    Figure --> "1" FigureStatus: figureStatus

    'DSLValidate -> x
    DSLValidate ..> "1" DSLDescription: validates

    'Exclusivity -> x
    Exclusivity --> "1" idExclusivity: id

    'Category -> x
    Category --> "1" idCategory: id
    Category --> "1" CategoryStatus: categoryStatus
}

package "Customer " <<aggregate>> {
    class Customer <<Entity>> <<root>>{
    }

    'Exclusivity -> x
    Exclusivity --> "1" Customer: exclusive to
}

@enduml