@startuml

package "Customer " {

    class Customer <<Entity>> <<root>>{
    }
}

package "Figure " <<aggregate>> {

    class Figure <<Entity>> <<root>>{
    }

    class FigureID <<Value Object>> <<ID>> {
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class DSLDescription <<Value Object>>{
    }

    enum FigureStatus <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }

    class DSLValidate <<Service>>{
    }

    'Figure -> x
    Figure --> "1" DSLDescription: DSLDescription
    Figure --> "1..*" Keyword: keywords
    Figure --> "0..1" Exclusivity: exclusivity
    Figure --> "1" FigureID: figureID
    Figure --> "1" FigureStatus: figureStatus

    'FigureID -> x
    FigureID --> "1" Code: code
    FigureID --> "1" Version: version

    'DSLValidate -> x
    DSLValidate ..> "1" DSLDescription: validates

    'Exclusivity -> x
    Exclusivity --> "1" Customer: exclusive to
}

package "Category " <<aggregate>>{

    class Category <<Entity>> <<root>>{
    }

    enum CategoryStatus <<Value Object>>{
    }

    'Category -> x
    Category --> "1" CategoryStatus: categoryStatus

    'Figure -> x
    Figure --> "1..*" Category: categories
}

package "ShowDesigner " <<aggregate>>{

    class ShowDesigner <<Entity>> <<root>>{
    }

    'Figure -> x
    Figure --> "1" ShowDesigner: created by
}

package Shared {

    class Time <<Value Object>>{
    }

    class Name <<Value Object>>{
    }

    class Email <<Value Object>>{
    }

    class PhoneNumber <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    'ShowDesigner -> x
    ShowDesigner --> "1" Name: name
    ShowDesigner --> "1" Email: email
    ShowDesigner --> "1" PhoneNumber: phoneNumber

    'Figure -> x
    Figure ----> "1" Description: description
    Figure ----> "1" Name: name

    'Category -> x
    Category ----> "1" Description: description
    Category ----> "1" Name: name
}

package "EAPLI Framework" <<framework>>{
    class DateInterval <<Value Object>>{
    }

    Exclusivity --> "1" DateInterval: duration
}

@enduml