@startuml

class Customer <<Entity>>{
    publicEntity
    vatNumber
    address
}

class Library <<Entity>>{
}

class Inventory <<Entity>>{
}

class Drone <<Entity>>{
    model
    serialNumber
    status
}

class Routine <<Entity>>{
    positions
}

class DSLValidate <<Service>>{

}

class Figure <<Entity>>{

}

class CRMCollaborator <<Entity>>{
    email
    name
    phoneNumber
}

class ShowDesigner <<Entity>>{
    name
    email
    phoneNumber
}

class DroneTech <<Entity>>{
    name
    email
    phoneNumber
}

class Representative <<Entity>>{
    position
    email
    name
}

class Show <<Entity>>{
    description
}

class Maintenance <<Entity>>{

}

class ShowRequest <<Entity>>{
    place
    qnt_drones
    duration
    startTime
    description
}

class ShowProposal <<Entity>>{

}


'Customer -> x
Customer  --> "1" ShowRequest : requests
Customer  --> "1..*" Representative : represented by
Customer --> "1..*" ShowProposal : analyzes

'ShowRequest -> x
ShowRequest --> "0..*" Figure : requests new


'ShowDesigner -> x
ShowDesigner --> "1..*" Figure: creates


'CRMCollaborator -> x
CRMCollaborator  --> "1" ShowProposal: generates
CRMCollaborator  --> "1" ShowRequest: submits
CRMCollaborator --> "1" Show : schedules

'Admin -> x

'DroneTech -> x
DroneTech --> "1..*" Figure: tests
DroneTech --> "1..*" Show: tests
DroneTech --> "1..*" Drone: configures

'Representative -> x


'Figure -> x
Figure --> "1..*" Drone: composed by
Figure ..> "1" DSLValidate: validates

'Show -> x
Show --> "1..*" Figure: sequence of

'Drone -> x
Drone --> "1" Routine: performs
Drone --> "0..*" Maintenance: sent for

'Library -> x
Library --> "0..*" Figure: contains

'Inventory -> x
Inventory --> "0..*" Drone: contains

'ShowProposal -> x


'Maintenance -> x




@enduml