@startuml

package "Drone " <<aggregate>> {

    class Drone <<Entity>> <<root>>{
    }

    class Maintenance <<Entity>>{
    }

    class MaintenanceDescription <<Value Object>>{
    }

    enum MaintenanceType <<Value Object>>{
    }

    class Model <<Value Object>>{
    }

    class SerialNumber <<Value Object>>{
    }

    enum DroneStatus <<Value Object>>{
    }

    'Drone -> x
    Drone --> "1" DroneStatus: status
    Drone --> "1" Model: model
    Drone --> "1" SerialNumber: serialNumber
    Drone --> "1" Maintenance: undergoes

    'Maintenance -> x
    Maintenance --> "1" MaintenanceDescription: description
    Maintenance --> "1" MaintenanceType: type
}

package Shared {

    class Date <<Value Object>>{
    }

    'Maintenance -> x
    Maintenance --> "1" Date: date
}

@enduml