@startuml

package "Customer " <<aggregate>> {
    class Customer <<Entity>> <<root>>{
    }

    class Representative <<Entity>>{
    }

    class Address <<Value Object>>{
    }

    class VatNumber <<Value Object>>{
    }

    enum CustomerStatus <<Value Object>>{
    }

    class Position <<Value Object>>{
    }

    'Customer -> x
    Customer  --> "1..*" Representative : represented by
    Customer --> "1" VatNumber : vat
    Customer --> "1" Address : address
    Customer --> "1" CustomerStatus : status

    'Representative -> x
    Representative --> "1" Position : position

}

package "Drone " <<aggregate>> {

    class Inventory <<Entity>>{
    }

    class Drone <<Entity>> <<root>>{
    }

    class Maintenance <<Entity>>{
    }

    class MaintenanceDescription <<Value Object>>{
    }

    enum MaintenanceType <<Value Object>>{
    }

    class Model <<Value Object>>{
    }

    class SerialNumber <<Value Object>>{
    }

    enum DroneStatus <<Value Object>>{
    }

    class Routine <<Value Object>>{
    }

    'Drone -> x
    Drone --> "1" Routine: performs
    Drone --> "1" DroneStatus: status
    Drone --> "1" Model: model
    Drone --> "1" SerialNumber: serialNumber
    Drone --> "1" Maintenance: undergoes

    'Inventory -> x
    Inventory o-- Drone

    'Maintenance -> x
    Maintenance --> "1" MaintenanceDescription: description
    Maintenance --> "1" MaintenanceType: type
}

package "Figure " <<aggregate>> {

    class Figure <<Entity>> <<root>>{
        + code: Integer
        + version: Double
        + description : String
    }

    class DSLDescription <<Value Object>>{
    }

    enum Category <<Value Object>>{
    }

    class SetOfKeywords <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }

    class Catalogue <<Entity>>{
    }

    class DSLValidate <<Service>>{
    }


    'Figure -> x
    Figure --> "1..*" Drone: composed by
    Figure --> "1" DSLDescription: description
    Figure --> "1" Category: category
    Figure --> "1" SetOfKeywords: keywords
    Figure --> "1" Exclusivity: exclusivity

    'DSLDescription -> x
    DSLDescription ..> "1" DSLValidate: validates

    'Catalogue -> x
    Catalogue o-- Figure

    'Exclusivity -> x
    Exclusivity --> "1" Customer: exclusive to
}

package "Show " <<aggregate>>{

    class Description <<Value Object>>{
    }

    enum ShowStatus <<Value Object>>{
    }

    class Location <<Value Object>>{
        + latitude: Double
        + longitude: Double
    }

    enum Status <<Value Object>>{
    }

    class ShowDescription <<Value Object>>{
    }

    class CRMCollaborator <<Entity>>{
        + id: Integer
    }

    class Show <<Entity>>{
    }

    class ShowRequest <<Entity>>{
        + qnt_drones: Integer
    }

    class ShowProposal <<Entity>>{
    }

    'ShowRequest -> x
    ShowRequest --> "0..*" Figure : requests new
    ShowRequest --> "1" Description : description
    ShowRequest --> "1" CRMCollaborator : submitted by
    ShowRequest --> "1" Customer: requested by
    ShowRequest --> "1" Location: place
    ShowRequest --> "1" Status: status

    'Show -> x
    Show --> "1..*" Figure: sequence of
    Show --> "1" ShowStatus: showStatus
    Show --> "1" ShowDescription: description
    Show --> "1" ShowProposal: generated with
    Show --> "1" CRMCollaborator : scheduled by

    'ShowProposal -> x
    ShowProposal --> "1" CRMCollaborator: generated by
    ShowProposal --> "1" ShowRequest: generated with
    ShowProposal --> "1" Status: status

}

package Shared {

    class Time <<Value Object>>{
    }

    class Name <<Value Object>>{
    }

    class Email <<Value Object>>{
    }

    class PhoneNumber <<Value Object>>{
    }

    class Date <<Value Object>>{
    }

    'CRM Collaborator -> x
    CRMCollaborator --> "1" Name: name
    CRMCollaborator --> "1" Email: email
    CRMCollaborator --> "1" PhoneNumber: phoneNumber

    'Exclusivity -> x
    Exclusivity --> "1" Time: duration

    'Representative -> x
    Representative --> "1" Name : name
    Representative --> "1" Email : email
    Representative --> "1" PhoneNumber : phoneNumber

    'ShowRequest -> x
    ShowRequest --> "1" Time : duration
    ShowRequest --> "1" Date : startTime

    'Show -> x
    Show --> "1" Date : date
    Show --> "1" Time : time

    'Maintenance -> x
    Maintenance --> "1" Date: date
}

@enduml