@startuml
actor "CRM Collaborator" as User
participant "SendProposalUI" as UI
participant "SendProposalController" as Controller
participant "PersistenceContext" as Persistence
participant "RepositoryFactory" as Factory
participant "ShowProposalRepository" as ProposalRepo
participant "ProposalDeliveryInfoRepository" as DeliveryRepo
participant "ProposalDeliveryInfo" as DeliveryInfo

activate User

User -> UI : request to send proposal
activate UI

UI -> Controller : listReadyToSendProposals()
activate Controller

Controller -> Persistence : PersistenceContext()
activate Persistence

Persistence -> Factory : repositories()
deactivate Persistence

activate Factory
Factory -> ProposalRepo : proposals()
deactivate Factory
activate ProposalRepo

ProposalRepo -> ProposalRepo : findProposalsReadyToSend()

ProposalRepo --> Controller : list of proposals
deactivate ProposalRepo

Controller --> UI : proposals
deactivate Controller

UI -> User : show proposals
User -> UI : select proposal

UI -> Controller : sendProposal(proposal, crmCollaborator)
activate Controller

Controller -> DeliveryInfo : sendProposal(proposal, crmCollaborator)
activate DeliveryInfo

DeliveryInfo --> Controller : delivery
deactivate DeliveryInfo

Controller -> Persistence : PersistenceContext()
activate Persistence

Persistence -> Factory : repositories()
deactivate Persistence

activate Factory
Factory -> DeliveryRepo : deliveries()
deactivate Factory
activate DeliveryRepo

DeliveryRepo -> DeliveryRepo : save(delivery)

DeliveryRepo --> Controller : saveDelivery
deactivate DeliveryRepo

Controller --> UI : show success + delivery code
UI --> User : show success message and code

deactivate Controller
deactivate UI
deactivate User
@enduml
