@startuml
set separator none

package "Domain" #DDDDDD {

    package "DTO" #DDDDDD {
        class CustomerDTO <<DTO>> {

        }

        class CustomerRepresentativeDTO <<DTO>> {

        }
    }

    package "Mapper" #DDDDDD {
        class CustomerListMapper <<Mapper>> {
            + toDTO(customer) : CustomerDTO
            + customersToDTO(customers) : List<CustomerDTO>
        }

        class CustomerRepresentativeListMapper <<Mapper>> {
            + toDTO(representative) : CustomerRepresentativeDTO
            + representativesToDTO(representatives) : List<CustomerRepresentativeDTO>
        }
    }

    package "Repository" #DDDDDD {
        Interface CustomerRepository <<Repository>> {
            + getCustomers() : List<Customer>
        }
        Interface CustomerRepresentativeRepository <<Repository>> {
            + getRepresentativesOfCustomer(customer, representative): List<CustomerRepresentative>
        }
        Interface Repositories <<Repository>> {
            - Repositories()
            + getInstance() : Repositories
            + getCustomerRepository() : CustomerRepository
            + getRepresentativeRepository() : CustomerRepresentativeRepository
        }
    }

    class Customer <<Entity>> {
        + Customer (name, address, vat, status, type)
    }
    class CustomerRepresentative <<Entity>> {
        + CustomerRepresentative (name, position, email, phoneNumber)
        + getRepresentativesOfCustomer(customer): List<CustomerRepresentative>
    }

    class Address <<Value Object>> {

    }
    class VatNumber <<Value Object>> {

    }
    enum CustomerStatus <<Value Object>> {

    }
    enum CustomerType <<Value Object>> {

    }
    class Position <<Value Object>> {

    }
    class Name <<Value Object>> {

    }
    class Email <<Value Object>> {

    }
    class PhoneNumber <<Value Object>> {

    }

    enum CustomerRepresentativeStatus <<Value Object>>{
    }
}

package "UI" #DDDDDD {
    class ListCustomerRepresentativesUI <<UI>> {

    }
}

package "Controller" #DDDDDD {
    class ListCustomerRepresentativesController <<Controller>> {
        + listRepresentativesOfAGivenCustomer(customer)
        + listAllCustomers()
    }
}

package "repositories.impl.jpa" #DDDDDD {
    class CustomerRepositoryJpaImpl <<Repository>> {
    }
    class CustomerRepresentativeRepositoryJpaImpl <<Repository>> {
    }
}

' Relações entre as classes

'CustomerRepositoryJpaImpl --> *
CustomerRepositoryJpaImpl ..|> CustomerRepository

'CustomerRepresentativeRepositoryJpaImpl --> *
CustomerRepresentativeRepositoryJpaImpl ..|> CustomerRepresentativeRepository

'Customer --> *
Customer --> "1..*" CustomerRepresentative : representative
Customer --> "1" VatNumber : vat
Customer --> "1" Address : address
Customer --> "1" CustomerStatus : status
Customer --> "1" CustomerType : type
Customer ----> "1" Name : name

'Representative --> *
CustomerRepresentative --> "1" Position : position
CustomerRepresentative --> "1" Name : name
CustomerRepresentative --> "1" Email : email
CustomerRepresentative --> "1" PhoneNumber : phoneNumber
CustomerRepresentative --> "1" CustomerRepresentativeStatus : status

'Repositories --> *
Repositories --> Repositories : instance
Repositories --> CustomerRepository : getCustomerRepository
Repositories --> CustomerRepresentativeRepository : getRepresentativeRepository

'CustomerRepository --> *
CustomerRepository --> "0..*" Customer : customers

'RepresentativeRepository --> *
CustomerRepresentativeRepository --> "0..*" CustomerRepresentative : representatives

'ListCustomerRepresentativesUI --> *
ListCustomerRepresentativesUI ..> ListCustomerRepresentativesController

'ListCustomerRepresentativesController --> *
ListCustomerRepresentativesController ..> Repositories : repositories
ListCustomerRepresentativesController ..> CustomerListMapper : customerListDTO
ListCustomerRepresentativesController ..> CustomerRepresentativeRepository : representativeRepository
ListCustomerRepresentativesController ..> CustomerRepository : customerRepository
ListCustomerRepresentativesController ..> CustomerRepresentativeListMapper : representativeListDTO

'CustomerDTO --> *
CustomerDTO ..> CustomerListMapper : customerDTO

'RepresentativeDTO --> *
CustomerRepresentativeDTO ..> CustomerRepresentativeListMapper : representativeDTO
@enduml