@startuml
set separator none

package "Domain" #DDDDDD {

    package "DTO" #DDDDDD {
        class CustomerDTO <<DTO>> {
        }
        class CustomerRepresentativeDTO <<DTO>> {
        }
    }

    package "Mapper" #DDDDDD {
        class CustomerListMapper <<Mapper>> {
            + toDTO(customer) : CustomerDTO
            + customersToDTO(customers) : List<CustomerDTO>
        }

        class CustomerRepresentativeListMapper <<Mapper>> {
            + toDTO(representative) : CustomerRepresentativeDTO
            + representativesToDTO(representatives) : List<CustomerRepresentativeDTO>
        }
    }

    package "Repository " #DDDDDD {
        Interface CustomerRepository <<Repository>> {
            + getCustomers() : List<Customer>
            + getRepresentativesOfCustomer(customer): List<CustomerRepresentative>
        }

        Interface RepositoryFactory <<Factory>> {
            - RepositoryFactory()
            + getCustomerRepository() : CustomerRepository
        }

        Interface Repository <<Repository>> {
            + save(entity T) : T
            + delete(entity T)
            + findById(id: String) : T
            + findAll() : List<T>
            + deleteById(id: ID)
            + count() : long
        }
    }

    class Customer <<Entity>> {
        + Customer(name, address, vat, status, type)
        + getRepresentatives() : List<CustomerRepresentative>
    }

    class CustomerRepresentative <<Entity>> {
        + CustomerRepresentative(name, position, email, phoneNumber)
    }

    class Address <<Value Object>> {
    }
    class VatNumber <<Value Object>> {
    }
    enum CustomerStatus <<Value Object>> {
    }
    enum CustomerType <<Value Object>> {
    }
    class Position <<Value Object>> {
    }
    class Name <<Value Object>> {
    }
    class Email <<Value Object>> {
    }
    class PhoneNumber <<Value Object>> {
    }
    enum CustomerRepresentativeStatus <<Value Object>> {
    }
}

package "UI" #DDDDDD {
    class ListCustomerRepresentativesUI <<UI>> {
    }
}

package "Controller" #DDDDDD {
    class ListCustomerRepresentativesController <<Controller>> {
        + listRepresentativesOfAGivenCustomer(customerId)
        + listAllCustomers()
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaCustomerRepository <<Repository>> {
    }

    class JpaRepositoryFactory <<Factory>> {
        - JpaRepositoryFactory()
        + getInstance() : RepositoryFactory
    }
}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryCustomerRepository <<Repository>> {
    }

    class InMemoryRepositoryFactory <<Factory>> {
        - InMemoryRepositoryFactory()
        + getInstance() : RepositoryFactory
    }
}

package "persistence" #DDDDDD {
    class PersistenceContext {
        getRepositoryFactory() : RepositoryFactory
    }
}

' Relationships
Customer --> "1..*" CustomerRepresentative : representatives
Customer --> "1" VatNumber : vat
Customer --> "1" Address : address
Customer --> "1" CustomerStatus : status
Customer --> "1" CustomerType : type
Customer ----> "1" Name : name

CustomerRepresentative --> "1" Position : position
CustomerRepresentative --> "1" Name : name
CustomerRepresentative --> "1" Email : email
CustomerRepresentative --> "1" PhoneNumber : phoneNumber
CustomerRepresentative --> "1" CustomerRepresentativeStatus : status

RepositoryFactory ..> CustomerRepository : getCustomerRepository()

CustomerRepository --> "0..*" Customer : customers

ListCustomerRepresentativesUI ..> ListCustomerRepresentativesController

ListCustomerRepresentativesController ..> RepositoryFactory : getCustomerRepository()
ListCustomerRepresentativesController ..> CustomerListMapper : customerListDTO
ListCustomerRepresentativesController ..> CustomerRepresentativeListMapper : representativeListDTO
ListCustomerRepresentativesController ..> CustomerRepository : getCustomers()
ListCustomerRepresentativesController ..> PersistenceContext : getRepositoryFactory()

CustomerDTO ..> CustomerListMapper : customerDTO
CustomerRepresentativeDTO ..> CustomerRepresentativeListMapper : customerRepresentativeDTO

PersistenceContext ..> JpaRepositoryFactory : getInstance()
PersistenceContext ..> InMemoryRepositoryFactory : getInstance()
PersistenceContext ..> RepositoryFactory : getCustomerRepository()

JpaRepositoryFactory ...|> RepositoryFactory : getCustomerRepository()
JpaRepositoryFactory ..> JpaCustomerRepository
JpaRepositoryFactory --> JpaRepositoryFactory : instance

JpaCustomerRepository ..|> CustomerRepository : getCustomers()

InMemoryRepositoryFactory .|> RepositoryFactory : getCustomerRepository()
InMemoryRepositoryFactory ..> InMemoryCustomerRepository
InMemoryRepositoryFactory --> InMemoryRepositoryFactory : instance

InMemoryCustomerRepository ..|> CustomerRepository : getCustomers()

CustomerRepository ..|> Repository

@enduml
