@startuml

actor User
participant Parent
participant Drone
participant CollisionThread
participant ReportThread
database InputFile
database Config
database ShmDrone
database ShmParent
database SemParent2Drone
database SemDrone2Parent

activate User
== Initialization ==

User -> Parent : Starts program
activate Parent

Parent -> Config : Read config / args
activate Config

Config --> Parent : Config data
deactivate Config
Parent -> Parent : Setup signals, allocs, semaphores and shared memory

Parent -> ShmParent : Create shared memory for Parent
activate ShmParent

Parent -> ShmDrone : Create shared memory for Drone
activate ShmDrone

Parent -> SemParent2Drone : Create semaphore for Parent to Drone communication
activate SemParent2Drone

Parent -> SemDrone2Parent : Create semaphore for Drone to Parent communication
activate SemDrone2Parent



== Drone Creation ==

loop For each drone
    Parent -> Parent : fork()
    Parent -> Drone : Creates child process
    activate Drone

        Drone -> Drone : Setup signals
        Drone -> Drone : Obtain the script
        Parent -> Parent : Store PID

end

== Threads ==

Parent -> CollisionThread : Create thread for collision
activate CollisionThread

Parent -> ReportThread : Create thread for report generation
activate ReportThread

CollisionThread -> CollisionThread : Run function thread_check_collisions
ReportThread -> ReportThread : Run function thread_do_report

== Simulation Loop ==
loop while drones active

    group Drone answer
        Drone -> InputFile : get position or vector
        activate InputFile
        Drone -> Drone : calculate position
        Drone -> ShmDrone : Write position to shared memory
        Drone -> SemDrone2Parent : Signal semaphore to Parent
    end

    group Parent read position
        Parent -> SemDrone2Parent : waits for semaphore
        Parent -> ShmDrone : Read position from shared memory
        Parent -> Parent : validate position and update is history
    end

    group Check Collisions
        CollisionThread -> CollisionThread : check_collisions()
        CollisionThread -> ShmParent : Read positions from shared memory
        alt Collision Detected
            CollisionThread -> Drone : SIGUSR1
            CollisionThread -> CollisionThread : update collision log
        end
    end

    alt Too Many Collisions
        Parent -> Drone : SIGUSR2
        Parent -> Parent : waitpid
        Parent -> Parent : generate report
        Parent -> Parent : terminate()
    else
        Parent -> SemParent2Drone : Signals semaphore for the drone to continue
    end

end
InputFile -> Drone : End of the file
deactivate InputFile
Drone -> ShmDrone : Mark end of file
Drone -> SemParent2Drone :  Signal semaphore to Parent
deactivate Drone

== Wrap Up ==

ReportThread -> ReportThread : do_report()
ReportThread -> ShmParent : Read all the data from shared memory
ReportThread -> User : Generate report and send to User
Parent -> Parent : terminate()
deactivate User
@enduml