@startuml
'skinparam monochrome

skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Drone Tech" as DT
participant "RegisterUsageTimeUI" as UI
participant "RegisterUsageTimeController" as CTRL
participant "PersistenceContext" as PERS
participant "RepositoryFactory" as REPOS
participant "DroneRepository" as DRONE_REPO

activate DT

DT -> UI : request to list drones from inventory
activate UI
    UI -> CTRL : findAllDronesInventory()
    activate CTRL

    CTRL --> PERS : repositories().drone()
    activate PERS
    PERS --> CTRL : DroneRepository
    deactivate PERS

    CTRL -> REPOS : getInstance()
    activate REPOS
    REPOS --> CTRL : repositories
    deactivate REPOS

    CTRL -> REPOS : drone()
    activate REPOS
    REPOS --> CTRL : DroneRepository
    deactivate REPOS

    CTRL -> DRONE_REPO : findAllDronesInventory()
    activate DRONE_REPO
    DRONE_REPO --> CTRL : activeDronesList
    deactivate DRONE_REPO

    CTRL --> UI : display drone list
    deactivate CTRL
UI --> DT : show drone list
deactivate UI

DT -> UI : selects drone and input usage time
activate UI
    UI -> CTRL : registerUsageTime(drone, usageTime)
    activate CTRL

    CTRL -> DRONE_REPO : save(drone)
    activate DRONE_REPO
    DRONE_REPO --> CTRL : drone saved
    deactivate DRONE_REPO

    CTRL --> UI : show success message
    deactivate CTRL
UI --> DT : display result (success or error)
deactivate UI
deactivate DT
@enduml
