@startuml
'https://plantuml.com/sequence-diagram
 class Model <<Entity>> <<root>>{
    }


  class Drone <<Entity>> <<root>>{
    }

    class SerialNumber <<Value Object>>{
    }

    enum DroneStatus <<Value Object>>{
    }

    'Drone -> x
    Drone --> "1" DroneStatus: status
    Drone --> "1" SerialNumber: serialNumber
    Drone --> "1" Model: uses

@enduml