@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "DroneTech" as EDT
participant ":ListDroneUI" as UI
participant ":ListDroneController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "modelRepository\n:ModelRepository" as MOD_REPO
participant "droneRepository\n:DroneRepository" as DRN_REPO
participant "drone\n:Drone" as DRONE

activate EDT

        EDT -> UI : asks to list an active drone
        activate UI
            UI --> CTRL** : create()

            UI -> CTRL : getDroneModelList()
                        activate CTRL
                            CTRL -> REPOS : getInstance()
                            activate REPOS
                                REPOS --> CTRL: repositories
                            deactivate REPOS

                            CTRL -> REPOS_SINGLETON : getModelRepository()
                            activate REPOS_SINGLETON
                                REPOS_SINGLETON --> CTRL: modelRepository
                            deactivate REPOS_SINGLETON

                            CTRL -> MOD_REPO : getModelList()
                            activate MOD_REPO
                                MOD_REPO --> CTRL : modelList
                            deactivate MOD_REPO
                            CTRL --> UI : modelList
                        deactivate CTRL
                   UI --> EDT : shows the list off all drone models and ask to select one
                           deactivate UI
                     EDT -> UI : selets one
                        activate UI
            UI --> UI : keepData(droneModel)
            UI -> CTRL : getActiveDroneList()
            activate CTRL
                CTRL -> REPOS : getInstance()
                activate REPOS
                    REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> REPOS_SINGLETON : getDroneRepository()
                activate REPOS_SINGLETON
                    REPOS_SINGLETON --> CTRL: droneRepository
                deactivate REPOS_SINGLETON

                CTRL -> DRN_REPO : getActiveDroneList(droneModel)
                activate DRN_REPO
                    DRN_REPO --> CTRL : activeDroneList
                deactivate DRN_REPO
                CTRL --> UI : activeDroneList
            deactivate CTRL

            UI --> EDT : shows the list off all activate drones and ask to select one
        deactivate UI



    EDT -> UI : selets one and ask to list in the inventory
    activate UI
    UI --> UI : keepData(activateDrone)
    UI --> EDT : requests confirmation
    deactivate UI
    EDT -> UI : confirms
    activate UI
        UI -> CTRL : listDrone(activateDrone)
        activate CTRL
             CTRL -> CTRL: getDroneRepository()
                                    activate CTRL

                                        CTRL -> REPOS: getInstance()
                                        activate REPOS

                                               REPOS --> CTRL: repositories

                                        deactivate REPOS

                                        CTRL -> REPOS_SINGLETON: getDroneRepository()
                                        activate REPOS_SINGLETON

                                               REPOS_SINGLETON --> CTRL: droneRepository
                                        deactivate REPOS_SINGLETON
                                    CTRL --> CTRL: droneRepository

                                    |||
                                                                        deactivate CTRL

                                    CTRL -> DRN_REPO : listDrone(activateDrone)
            activate DRN_REPO
                DRN_REPO -> DRONE **: list(activateDrone)
                    DRN_REPO -> DRN_REPO: validateDrone(activateDrone)
                    activate DRN_REPO
                        DRN_REPO --> DRN_REPO : true
                    deactivate DRN_REPO

                DRN_REPO --> CTRL : true
            deactivate DRN_REPO

            CTRL --> UI: true
            deactivate CTRL
            UI --> EDT: displays operation success
    deactivate UI

deactivate EDT

@enduml