@startuml
actor "CustomerRepresentative" as User
participant "AnalyseProposalUI" as UI
participant "AnalyseProposalController" as Controller

participant "CustomerAppProtocolProxy" as Proxy

participant "GetShodroneUserRequest" as RequestUser
participant "GetCustomerOfRepresentativeRequest" as REQUEST_CUST_REPRESENTATIVE
participant "GetProposalByCodeRequest" as GetProposalsRequest

participant "ClientSocket" as Socket

participant "CustomerAppServer" as Server

participant "CustomerAppMessageParser" as Parser

participant "DatabaseProcessor" as DBPROC

participant "GetShodroneUserRequest" as GetShodroneUserRequestDAEMON
participant "GetCustomerRequest" as GetCustomerRequest
participant "GetPropByCodeRequest" as RequestDAEMON

participant "UserAppServerController" as ServerController

participant "ShodroneUserRepository" as ShodroneUserRepo
participant "CustomerRepository" as CustomerRepo
participant "DeliveryReportingRepository" as DeliveryRepo

participant "MarshallerUnmarshaller" as MU

participant "ShodroneUserDTO" as UserDTO
participant "CustomerDTO" as CustomerDTO
participant "ProposalDTO" as ProposalDTO



activate User

User -> UI : request to analyse an show proposal
activate UI
UI --> User : asks for delivery code
User -> UI : provides delivery code

UI -> Controller : findProposalByDeliveryCode(code)
activate Controller
Controller -> Controller : findProposalByDeliveryCode(code)
activate Controller
Controller -> Proxy : getShodroneUser(currentUser)
activate Proxy

Proxy -> RequestUser : toRequest(currentUser.username)
activate RequestUser
RequestUser --> Proxy : request
deactivate RequestUser

Proxy -> Socket : connect()
activate Socket
Proxy -> Socket : sendAndReceive(request)

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Parser -> GetShodroneUserRequestDAEMON : parseGetShodroneUser(request)
activate GetShodroneUserRequestDAEMON
GetShodroneUserRequestDAEMON --> Parser : new GetShodroneUserRequest(request)
deactivate GetShodroneUserRequestDAEMON
Parser -> DBPROC : run()
activate DBPROC
DBPROC -> GetShodroneUserRequestDAEMON : execute()
activate GetShodroneUserRequestDAEMON
GetShodroneUserRequestDAEMON -> ServerController : getShodroneUserByUsername(username)
activate ServerController
ServerController -> ShodroneUserRepo : findByUsername(username)
activate ShodroneUserRepo
ShodroneUserRepo --> ServerController : shodroneUser
deactivate ShodroneUserRepo

ServerController --> GetShodroneUserRequestDAEMON : shodroneUser
deactivate ServerController
GetShodroneUserRequestDAEMON -> GetShodroneUserRequestDAEMON : buildResponse(shodroneUser)
activate GetShodroneUserRequestDAEMON
GetShodroneUserRequestDAEMON --> GetShodroneUserRequestDAEMON : response
deactivate GetShodroneUserRequestDAEMON
GetShodroneUserRequestDAEMON --> DBPROC : response
deactivate GetShodroneUserRequestDAEMON
DBPROC --> Parser : response
deactivate DBPROC

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageShodroneUser(response)
activate MU

MU -> UserDTO : new ShodroneUserDTO(response)
activate UserDTO
UserDTO --> MU
deactivate UserDTO

MU --> Proxy : shodroneUserDTO
deactivate MU

Proxy --> Controller : shodroneUserDTO
deactivate Proxy

Controller -> Proxy : getCustomerOfRepresentative(shodroneUserDTO.email)
activate Proxy

Proxy -> REQUEST_CUST_REPRESENTATIVE : toRequest(shodroneUserDTO.email)
activate REQUEST_CUST_REPRESENTATIVE
REQUEST_CUST_REPRESENTATIVE --> Proxy : request
deactivate REQUEST_CUST_REPRESENTATIVE

Proxy -> Socket : connect()
activate Socket
Proxy -> Socket : sendAndReceive(request)


Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser
Parser -> GetCustomerRequest : parseGetCustomer(request)
activate GetCustomerRequest
GetCustomerRequest --> Parser : new GetCustomerRequest(request)
deactivate GetCustomerRequest

Parser -> DBPROC : run()
activate DBPROC
DBPROC -> GetCustomerRequest : execute()
activate GetCustomerRequest
GetCustomerRequest -> ServerController : getCustomerByRepresentativeEmail(repEmail)
activate ServerController
ServerController -> CustomerRepo : findCustomerByRepresentativeEmail(repEmail)
activate CustomerRepo
CustomerRepo --> ServerController : customer
deactivate CustomerRepo

ServerController --> GetCustomerRequest : customer
deactivate ServerController
GetCustomerRequest -> GetCustomerRequest : buildResponse(customer)
activate GetCustomerRequest
GetCustomerRequest --> GetCustomerRequest : response
deactivate GetCustomerRequest
GetCustomerRequest --> DBPROC : response
deactivate GetCustomerRequest
DBPROC --> Parser : response
deactivate DBPROC

deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageCustomer(response)
activate MU

MU -> CustomerDTO : new CustomerDTO(response)
activate CustomerDTO
CustomerDTO --> MU
deactivate CustomerDTO

MU --> Proxy : customerDTO
deactivate MU

Proxy --> Controller : customerDTO
deactivate Proxy


Controller -> Proxy : getProposalByCode(code)
activate Proxy

Proxy -> GetProposalsRequest : toRequest(code)
activate GetProposalsRequest
GetProposalsRequest --> Proxy : request
deactivate GetProposalsRequest

Proxy -> Socket : connect()
activate Socket
Proxy -> Socket : sendAndReceive(request)

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser
Parser -> RequestDAEMON : parseGetProposalByCode(request)
activate RequestDAEMON
RequestDAEMON --> Parser : new GetProposalByCode(request)
deactivate RequestDAEMON

Parser -> DBPROC : run()
activate DBPROC
DBPROC -> RequestDAEMON : execute()
activate RequestDAEMON
RequestDAEMON -> ServerController : findProposalByDeliveryCode(code)
activate ServerController
ServerController -> DeliveryRepo : findProposalByDeliveryCode(code)
activate DeliveryRepo
DeliveryRepo --> ServerController : deliveryReport
deactivate DeliveryRepo

ServerController --> RequestDAEMON : deliveryReport
deactivate ServerController
RequestDAEMON -> RequestDAEMON : buildResponse(deliveryReport)
activate RequestDAEMON
RequestDAEMON --> RequestDAEMON : response
deactivate RequestDAEMON
RequestDAEMON --> DBPROC : response
deactivate RequestDAEMON
DBPROC --> Parser : response
deactivate DBPROC

deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageProposal(response)
activate MU

MU -> ProposalDTO : new ShowProposalDTO(response)
activate ProposalDTO
ProposalDTO --> MU
deactivate ProposalDTO

MU --> Proxy : showProposalDTO
deactivate MU

Proxy --> Controller : showProposalDTO
deactivate Proxy
Controller --> Controller : showProposalDTO
deactivate Controller
Controller -> Controller : validateFile(customerdto, showProposalDTO)
activate Controller
Controller -> Controller : true
deactivate Controller
Controller -> UI : showProposalDTO
deactivate Controller

UI -> Controller :decodeFile(showProposalDTO.file)
activate Controller
Controller --> UI : fyleBytes
deactivate Controller
UI -> Controller : createFile(fyleBytes, showProposalDTO)
activate Controller
Controller --> UI : filePath
deactivate Controller

UI --> User : File created successfully, here is the path: filePath
deactivate UI
deactivate User

@enduml