@startuml
actor "CustomerRepresentative" as User
participant "AnalyseProposalUI" as UI
participant "AnalyseProposalController" as Controller
participant "CustomerAppProtocolProxy" as Proxy
participant "GetShodroneUserRequest" as RequestUser
participant "ClientSocket" as Socket
participant "CustomerAppServer" as Server
participant "CustomerAppMessageParser" as Parser
participant "DatabaseProcessor" as DBPROC
participant "GetPropByCodeRequest" as RequestDAEMON
participant "UserAppServerController" as ServerController
participant "ShodroneUserRepository" as ShodroneUserRepo
participant "MarshallerUnmarshaller" as MU
participant "ShodroneUserDTO" as UserDTO
participant "GetCustomerOfRepresentativeRequest" as GetCustomerRequest
participant "CustomerDTO" as CustomerDTO
participant "CustomerRepository" as CustomerRepo
participant "GetProposalByCodeRequest" as GetProposalsRequest
participant "DeliveryReportingRepository" as DeliveryRepo
participant "ProposalDTO" as ProposalDTO
participant "SendFeedbackProposalRequest" as Request
participant "ShowProposalRepository" as ProposalRepo
participant "SendFeedbackProposalResponse" as Response


activate User

User -> UI : request to analyse an show proposal
activate UI
UI --> User : asks for delivery code
User -> UI : provides delivery code

UI -> Controller : findProposalByDeliveryCode(code)
activate Controller

Controller -> Proxy : getShodroneUser(authenticatedUser)
activate Proxy

Proxy -> RequestUser : toRequest(authenticatedUser)
activate RequestUser
deactivate RequestUser

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Parser -> ServerController : getShodroneUserByUsername(username)
activate ServerController

ServerController -> ShodroneUserRepo : findByUsername(username)
activate ShodroneUserRepo
deactivate ShodroneUserRepo

ServerController --> Parser : response
deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageShodroneUser(response)
activate MU

MU -> UserDTO : ShodroneUserDTO()
activate UserDTO
deactivate UserDTO

MU --> Proxy : parseResponseMessageLineShodroneUser(response)
deactivate MU

Proxy --> Controller : shodroneUser
deactivate Proxy



Controller -> Proxy : getCustomerOfRepresentative(shodroneUser)
activate Proxy

Proxy -> GetCustomerRequest : toRequest(authenticatedUser)
activate GetCustomerRequest
deactivate GetCustomerRequest

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Server -> Parser : execute(request)

Parser -> ServerController : getCustomerByRepresentativeEmail(repEmail)
activate ServerController

ServerController -> CustomerRepo : findCustomerByRepresentativeEmail(repEmail)
activate CustomerRepo
deactivate CustomerRepo

ServerController --> Parser : response
deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageCustomer(response)
activate MU

MU -> CustomerDTO : CustomerDTO()
activate CustomerDTO
deactivate CustomerDTO

MU --> Proxy : parseResponseMessageLineCustomer(response)
deactivate MU



Proxy --> Controller : customer
deactivate Proxy

Controller -> Proxy : getProposalByCode(code)
activate Proxy

Proxy -> GetProposalsRequest : toRequest(customer)
activate GetProposalsRequest
GetProposalsRequest --> Proxy : request
deactivate GetProposalsRequest

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser
Parser -> RequestDAEMON : parseGetProposalByCode(request)
activate RequestDAEMON
RequestDAEMON --> Parser : new GetProposalByCode(request)
deactivate RequestDAEMON

Parser -> DBPROC : run()
activate DBPROC
DBPROC -> RequestDAEMON : execute()
activate RequestDAEMON
RequestDAEMON -> ServerController : findProposalByDeliveryCode(code)
activate ServerController
ServerController -> DeliveryRepo : findProposalByDeliveryCode(code)
activate DeliveryRepo
DeliveryRepo --> ServerController : deliveryReport
deactivate DeliveryRepo

ServerController --> RequestDAEMON : deliveryReport
deactivate ServerController
RequestDAEMON -> RequestDAEMON : buildResponse(deliveryReport)
activate RequestDAEMON
RequestDAEMON --> RequestDAEMON : response
deactivate RequestDAEMON
RequestDAEMON --> DBPROC : response
deactivate RequestDAEMON
DBPROC --> Parser : response
deactivate DBPROC

deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageProposal(response)
activate MU

MU -> ProposalDTO : new ShowProposalDTO()
activate ProposalDTO
ProposalDTO --> MU
deactivate ProposalDTO

MU --> Proxy : showProposalDTO
deactivate MU

Proxy --> Controller : showProposalDTO
deactivate Proxy

Controller --> UI : showProposalDTO
deactivate Controller

UI -> Controller :decodeFile(proposalDTO.file)
activate Controller
Controller --> UI : fyleBytes
deactivate Controller
UI -> Controller : createFile(fyleBytes, showProposalDTO)
activate Controller
Controller --> UI : filePath
deactivate Controller

UI --> User : File created successfully, here is the path: filePath
deactivate UI
deactivate User

@enduml