@startuml
actor "Customer Representative" as User
participant "ShowInfoUI" as UI
participant "ShowInfoController" as Controller
participant "CustomerAppProtocolProxy" as Proxy
participant "CustomerAppServer" as Server
participant "CustomerAppMessageParser" as Parser
participant "UserAppServerController" as ServerController
participant "MarshlerUnmarshler" as MU
participant "GetShodroneUserRequest" as ReqUser
participant "ShodroneUserDTO" as UserDto
participant "CustomerDTO" as CustDto
participant "ShowDTO" as ShowDto
participant "ShodroneUserRepository" as ShodroneUserRepo
participant "CustomerRepository" as CustRepo
participant "ShowReportingRepository" as ShowRepo

activate User

User -> UI : request to show the info of a scheduled show
activate UI

UI -> Controller : listShows()
activate Controller

Controller -> Controller : getRepresenteeOfCustomer()

activate Controller

Controller -> Proxy : getShodroneUser(authenticatedUser)

activate Proxy

Proxy -> ReqUser : toRequest(authenticatedUser)

Proxy -> Proxy : socket.sendAndRecv(request)

activate Proxy

Proxy -> Server : sendRequest(request)

activate Server

Server -> Parser : parse(request)

Server -> Parser : execute(request)

activate Parser

Parser -> ServerController : parseGetShodroneUser()

activate ServerController

ServerController -> ShodroneUserRepo : getShodroneUserByUsername(username)


ServerController -> Parser : response

deactivate ServerController

Parser -> Server : response
deactivate Parser
Server -> Proxy : response

deactivate Server



Proxy -> MU : parseResponseMessageShodroneUser(response)

activate MU

MU -> UserDto : ShodroneUserDTO()

MU -> Proxy : parseResponseMessageLineShodroneUser(response)

deactivate MU


deactivate Proxy

Proxy -> Controller : shodroneUser

deactivate Proxy

Controller -> Proxy : getCustomerOfRepresentative(shodroneUser)


activate Proxy
Proxy -> CustDto : toRequest(authenticatedUser)

Proxy -> Proxy : socket.sendAndRecv(request)

activate Proxy

Proxy -> Server : sendRequest(request)

activate Server

Server -> Parser : parse(request)

Server -> Parser : execute(request)

activate Parser

Parser -> ServerController : GetCustomerRequest()

activate ServerController

ServerController -> CustRepo : getCustomerByRepresentativeEmail(String repEmail)


ServerController -> Parser : response

deactivate ServerController

Parser -> Server : response
deactivate Parser
Server -> Proxy : response

deactivate Server


Proxy -> MU : parseResponseMessageCustomer(response)

activate MU

MU -> CustDto : CustomerDTO()

MU -> Proxy : parseResponseMessageLineCustomer(response)

deactivate MU

deactivate Proxy

Proxy -> Controller : customer
deactivate Proxy

deactivate Controller

Controller -> Proxy : getShowsByCustomer(customer)

activate Proxy

Proxy -> ShowDto : toRequest(customer)

Proxy -> Proxy : socket.sendAndRecv(request)
activate Proxy

Proxy -> Server : sendRequest(request)

activate Server

Server -> Parser : parse(request)

Server -> Parser : execute(request)

activate Parser

Parser -> ServerController : GetShowsRequest()

activate ServerController

ServerController -> ShowRepo : findShowsOfCustomer(vatNumber)


ServerController -> Parser : response

deactivate ServerController

Parser -> Server : response
deactivate Parser
Server -> Proxy : response

deactivate Server


Proxy -> MU : parseResponseMessageShow(response)
activate MU
MU -> ShowDto : ShowDTO()

MU -> Proxy : parseResponseMessageLineShow(response)
deactivate MU

deactivate Proxy


Proxy -> Controller : shows

deactivate Proxy
Controller -> UI : shows
deactivate Controller
UI -> User : asks to select a show

User -> UI : selects a show

UI -> Controller : obtainShow(selectedShow)

activate Controller

Controller -> UI : show

deactivate Controller
UI -> User : show info of show

deactivate UI
deactivate User

@enduml