@startuml
actor "Customer" as User
participant "ShowInfoUi" as UI
participant "ShowInfoController" as Controller
participant "CustomerAppProtocolProxy" as Proxy
participant "GetShodroneUserRequest" as RequestUser
participant "ClientSocket" as Socket
participant "CustomerAppServer" as Server
participant "CustomerAppMessageParser" as Parser
participant "UserAppServerController" as ServerController
participant "ShodroneUserRepository" as ShodroneUserRepo
participant "MarshallerUnmarshaller" as MU
participant "ShodroneUserDTO" as UserDTO
participant "GetCustomerOfRepresentativeRequest" as GetCustomerRequest
participant "CustomerDTO" as CustomerDTO
participant "CustomerRepository" as CustomerRepo
participant "GetShowsOfCustomerRequest" as GetShowsRequest
participant "ShowDTO" as ShowDTO
participant "ShowReportingRepository" as ShowRepo

activate User

User -> UI : request to show info of a show
activate UI

UI -> Controller : listShows()
activate Controller

Controller -> Proxy : getShodroneUser(authenticatedUser)
activate Proxy

Proxy -> RequestUser : toRequest(authenticatedUser)
activate RequestUser
deactivate RequestUser

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Server -> Parser : execute(request)

Parser -> ServerController : getShodroneUserByUsername(username)
activate ServerController

ServerController -> ShodroneUserRepo : findByUsername(username)
activate ShodroneUserRepo
deactivate ShodroneUserRepo

ServerController --> Parser : response
deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageShodroneUser(response)
activate MU

MU -> UserDTO : ShodroneUserDTO()
activate UserDTO
deactivate UserDTO

MU --> Proxy : parseResponseMessageLineShodroneUser(response)
deactivate MU

Proxy --> Controller : shodroneUser
deactivate Proxy



Controller -> Proxy : getCustomerOfRepresentative(shodroneUser)
activate Proxy

Proxy -> GetCustomerRequest : toRequest(authenticatedUser)
activate GetCustomerRequest
deactivate GetCustomerRequest

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Server -> Parser : execute(request)

Parser -> ServerController : getCustomerByRepresentativeEmail(repEmail)
activate ServerController

ServerController -> CustomerRepo : findCustomerByRepresentativeEmail(repEmail)
activate CustomerRepo
deactivate CustomerRepo

ServerController --> Parser : response
deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageCustomer(response)
activate MU

MU -> CustomerDTO : CustomerDTO()
activate CustomerDTO
deactivate CustomerDTO

MU --> Proxy : parseResponseMessageLineCustomer(response)
deactivate MU



Proxy --> Controller : customer
deactivate Proxy

Controller -> Proxy : getShows(vatNumber)
activate Proxy

Proxy -> GetShowsRequest : toRequest(customer)
activate GetShowsRequest
deactivate GetShowsRequest

Proxy -> Socket : sendAndReceive(request)
activate Socket

Socket -> Server : send(request)
activate Server

Server -> Parser : parse(request)
activate Parser

Server -> Parser : execute(request)

Parser -> ServerController : getShowsByVatNumber(vatNumber)
activate ServerController

ServerController -> ShowRepo : findShowsOfCustomer(vatNumber)
activate ShowRepo
deactivate ShowRepo

ServerController --> Parser : response
deactivate ServerController

Parser --> Server : response
deactivate Parser

Server --> Socket : response
deactivate Server

Socket --> Proxy : response
deactivate Socket

Proxy -> MU : parseResponseMessageShow(response)
activate MU

MU -> ShowDTO : ShowDTO()
activate ShowDTO
deactivate ShowDTO

MU --> Proxy : parseResponseMessageLineShow(response)
deactivate MU

Proxy --> Controller : shows
deactivate Proxy

Controller --> UI : shows
deactivate Controller

UI --> User : asks to select a show

User -> UI : selects a show

UI -> Controller : obtainShow(selectedShow)

activate Controller

Controller -> UI : show

deactivate Controller
UI -> User : show info of show

deactivate UI
deactivate User

@enduml