@startuml

package "Category " <<aggregate>>{

    class Category <<Entity>> <<root>>{
    }

    class CategoryDescription <<Value Object>>{
    }

    enum CategoryStatus <<Value Object>>{
    }

    class CategoryName <<Value Object>>{
    }

    'Category -> x
    Category --> "1" CategoryStatus: categoryStatus
    Category --> "1" CategoryName: name
    Category --> "1" CategoryDescription: description

@enduml