@startuml

package "Customer " {

    class Customer <<Entity>> <<root>>{
    }
}

package "Figure " <<aggregate>> {

    class Figure <<Entity>> <<root>>{
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    enum FigureStatus <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }


    'Figure -> x
    Figure --> "1..*" Keyword: keywords
    Figure --> "1" Exclusivity: exclusivity
    Figure --> "1" Code: code
    Figure --> "1" Version: version
    Figure --> "1" Description: description
    Figure --> "1" FigureStatus: figureStatus

    'Exclusivity -> x
    Exclusivity --> "1" Customer: exclusive to
}

package "Category " <<aggregate>>{

    class Category <<Entity>> <<root>>{
    }

    class CategoryName <<Value Object>>{
    }

    'Category -> x
    Category --> "1" CategoryName: name

    'Figure -> x
    Figure --> "1..*" Category: category
}

package Shared {
    class Name <<Value Object>>{
    }

    Customer --> "1" Name: name
}

@enduml