@startuml
set separator none

package "Persistence " #DDDDDD {
    class PersistenceContext {
        + getRepositoryFactory(): RepositoryFactory
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaRepositoryFactory {
        - JpaRepositoryFactory()
        + getInstance(): RepositoryFactory
    }

    class JpaFigureRepository {
    }

    class JpaCategoryRepository {
    }

}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryRepositoryFactory {
        - InMemoryRepositoryFactory()
        + getInstance(): RepositoryFactory
    }

    class InMemoryFigureRepository {
    }

    class InMemoryCategoryRepository {
    }
}

package "Domain" #DDDDDD {

    package "Repository " #DDDDDD {

        interface RepositoryFactory {
            + getCategoryRepository(): CategoryRepository
        }

        interface FigureRepository {
            + addFigureToCatalogue(figure)
        }

        interface CategoryRepository {
            + allCategories(): List<Category>
        }

    }

    'Figure Aggregate
    class Figure <<Entity>>{
        + Figure(code, version, description, dslDescription, keywords, category)
        + Figure(code, version, description, dslDescription, keywords, category, exclusivity)
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    class DSLDescription <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }


    'Category Aggregate
    class Category <<Entity>>{
    }


    'ShowDesigner Aggregate
    class ShowDesigner <<Entity>>{
    }

}

package "UI" #DDDDDD {
    class AddFigureToCatalogueUI <<UI>> {
        + addFigureToCatalogue(figure)
        + showCategories()
    }
}

package "Controller" #DDDDDD {
    class AddFigureToCatalogueController <<Controller>> {
        + addFigureToCatalogue(figure)
        + listCategories()
    }
}

'Persistence

    'PersistenceContext -> x
    PersistenceContext ..> RepositoryFactory: figureRepository()\ncategoryRepository()
    PersistenceContext ..> JpaRepositoryFactory
    PersistenceContext ..> InMemoryRepositoryFactory

'persistence.impl.jpa

    'JpaFigureRepository -> x
    JpaFigureRepository --|> FigureRepository

    'JpaCategoryRepository -> x
    JpaCategoryRepository --|> CategoryRepository

    'JpaRepositoryFactory -> x
    JpaRepositoryFactory ....|> RepositoryFactory
    JpaRepositoryFactory ..> JpaFigureRepository
    JpaRepositoryFactory ..> JpaCategoryRepository

'persistence.impl.inmemory

    'InMemoryFigureRepository -> x
    InMemoryFigureRepository ..|> FigureRepository

    'InMemoryCategoryRepository -> x
    InMemoryCategoryRepository ..|> CategoryRepository

    'InMemoryRepositoryFactory -> x
    InMemoryRepositoryFactory ...|> RepositoryFactory
    InMemoryRepositoryFactory ..> InMemoryFigureRepository
    InMemoryRepositoryFactory ..> InMemoryCategoryRepository

'Repository

    'FigureRepository -> x
    FigureRepository ...> Figure

    'CategoryRepository -> x
    CategoryRepository ...> Category

    'RepositoryFactory -> x
    RepositoryFactory ..> FigureRepository
    RepositoryFactory ..> CategoryRepository

'Domain

    'Figure -> x
    Figure --> "1" DSLDescription: DSLDescription
    Figure --> "1..*" Keyword: keywords
    Figure --> "1" Code: code
    Figure --> "1" Version: version
    Figure --> "1" Description: description
    Figure --> "1" Category: category
    Figure --> "1" ShowDesigner: created by
    Figure --> "0..1" Exclusivity: exclusivity

'UI

    'AddFigureToCatalogueUI -> x
    AddFigureToCatalogueUI ..> AddFigureToCatalogueController

'Controller

    'AddFigureToCatalogueController -> x
    AddFigureToCatalogueController ..> PersistenceContext : getRepositoryFactory()
    AddFigureToCatalogueController ..> RepositoryFactory : getFigureRepository()
    AddFigureToCatalogueController ..> RepositoryFactory : getCategoryRepository()
    AddFigureToCatalogueController ..> FigureRepository : addFigureToCatalogue(figure)
    AddFigureToCatalogueController ..> CategoryRepository : allCategories()


@enduml