@startuml

package "Figure " <<aggregate>> {

    class Figure <<Entity>> <<root>>{
    }

    class Code <<Value Object>>{
    }

    class Version <<Value Object>>{
    }

    class Description <<Value Object>>{
    }

    class DSLDescription <<Value Object>>{
    }

    class Keyword <<Value Object>>{
    }

    class Exclusivity <<Entity>>{
    }


    'Figure -> x
    Figure --> "1" DSLDescription: DSLDescription
    Figure --> "1..*" Keyword: keywords
    Figure --> "1" Exclusivity: exclusivity
    Figure --> "1" Code: code
    Figure --> "1" Version: version
    Figure --> "1" Description: description

}

package "Category " <<aggregate>>{

    class Category <<Entity>> <<root>>{
    }

    'Figure -> x
    Figure --> "1..*" Category: categories
}

package "ShowDesigner " <<aggregate>>{

    class ShowDesigner <<Entity>> <<root>>{
    }

    'Figure -> x
    Figure --> "1" ShowDesigner: created by
}

@enduml