@startuml
set separator none
left to right direction


package "Domain" #DDDDDD {

    package "Repository " #DDDDDD {
        Interface ShowProposalRepository <<Repository>> {
            + findAllTestingProposalsByShowRequest(request) : Iterable<ShowProposal>

        }

        Interface RepositoryFactory <<Factory>> {
            - RepositoryFactory()
            + proposals() : ShowProposalRepository
        }

        Interface ShowRequestRepository <<Repository>> {
            + findAllCreatedShowRequests() : Iterable<ShowRequest>
        }

    }


        class ShowRequest <<Entity>> <<root>> {

        }
        class ShowProposal <<Entity>> <<root>>{
        }

        class Video <<Value Object>>{
        }

        class VideoList {
        }
}

package "UI" #DDDDDD {
    class AddVideoToProposalUI <<UI>> {

    }
}

package "Controller" #DDDDDD {
    class AddVideoToProposalController <<Controller>> {
        + findAllTestingProposalsByShowRequest(request) : Iterable<ShowProposal>
        + findAllCreatedShowRequests() : Iterable<ShowRequest>
        + listVideos()
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaShowProposalRepository <<Repository>> {
        + findAllTestingProposalsByShowRequest(request) : Iterable<ShowProposal>
    }

    class JpaRepositoryFactory <<Factory>> {
        - JpaRepositoryFactory()
        + proposals() : ShowProposalRepository
    }

    class JpaShowRequestRepository <<Repository>> {
        + findAllCreatedShowRequests() : Iterable<ShowRequest>
    }
}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryShowProposalRepository <<Repository>> {
        + findAllTestingProposals() : Iterable<ShowProposal>
    }

    class InMemoryRepositoryFactory <<Factory>> {
        - InMemoryRepositoryFactory()
        + proposals() : ShowProposalRepository
    }

    class InMemoryShowRequestRepository <<Repository>> {
        + findAllCreatedShowRequests() : Iterable<ShowRequest>
    }
}

package "persistence" #DDDDDD {
    class PersistenceContext {
        repositories() : RepositoryFactory
    }
}

' Relações entre as classes

ShowProposal --> "1" Video: video
ShowProposal --> "1" ShowRequest: based on


RepositoryFactory ..> ShowProposalRepository : proposals()
ShowProposalRepository ..> ShowRequestRepository : showRequest()

ShowProposalRepository --> "0..*" ShowProposal : proposals
ShowRequestRepository --> "0..*" ShowRequest : requests

AddVideoToProposalUI ..> AddVideoToProposalController
AddVideoToProposalController ..> RepositoryFactory : proposals()
AddVideoToProposalController ..> RepositoryFactory : showRequest()
AddVideoToProposalController ..> ShowRequestRepository : showRequest()
AddVideoToProposalController ..> ShowProposalRepository : proposals()
AddVideoToProposalController ..> PersistenceContext : repositories()

AddVideoToProposalController ..> VideoList : listVideos()

PersistenceContext ..> JpaRepositoryFactory : JpaRepositoryFactory()
PersistenceContext ..> InMemoryRepositoryFactory : InMemoryRepositoryFactory()
PersistenceContext ..> RepositoryFactory : proposals()
PersistenceContext ..> RepositoryFactory : showRequest()

JpaRepositoryFactory ...|> RepositoryFactory : proposals()
JpaRepositoryFactory ...|> RepositoryFactory : showRequest()
JpaRepositoryFactory ..> JpaShowProposalRepository
JpaRepositoryFactory ..> JpaShowRequestRepository

JpaShowProposalRepository ..|> ShowProposalRepository : findAllTestingProposalsByShowRequest(request)

JpaShowRequestRepository ..|> ShowRequestRepository : findAllCreatedShowRequests()



InMemoryRepositoryFactory .|> RepositoryFactory : proposals()
InMemoryRepositoryFactory .|> RepositoryFactory : showRequest()

InMemoryRepositoryFactory ..> InMemoryShowProposalRepository
InMemoryRepositoryFactory ..> InMemoryShowRequestRepository

InMemoryShowProposalRepository ..|> ShowProposalRepository : findAllTestingProposalsByShowRequest(request)
InMemoryShowRequestRepository ..|> ShowRequestRepository : findAllCreatedShowRequests()


@enduml