@startuml
actor "CRM Collaborator" as User
participant "AddVideoToProposalUI" as UI
participant "AddVideoToProposalController" as Controller
participant "VideoList" as List
participant "PersistenceContext" as Persistence
participant "RepositoryFactory" as Factory
participant "ShowRequestRepository" as ShowRequestRepo
participant "ShowProposalRepository" as ShowProposalRepo
participant "ShowProposal" as Proposal

activate User

User -> UI : request to add a video to the proposal
activate UI

UI -> Controller : listShowRequests()
activate Controller

Controller -> Persistence : PersistenceContext()
activate Persistence

Persistence -> Factory : repositories()
deactivate Persistence

activate Factory
Factory -> ShowRequestRepo : showRequest()
deactivate Factory

activate ShowRequestRepo

ShowRequestRepo -> ShowRequestRepo : findAllCreatedShowRequests()
activate ShowRequestRepo

ShowRequestRepo -> Controller : showRequests
deactivate ShowRequestRepo

deactivate ShowRequestRepo

Controller -> UI : showRequests
deactivate Controller
UI -> User : asks to select a show request
User -> UI : selects a show request

UI -> Controller : listProposals(showRequest)

activate Controller

Controller -> Persistence : PersistenceContext()
activate Persistence

Persistence -> Factory : repositories()
deactivate Persistence


activate Factory
Factory -> ShowProposalRepo : proposals()

deactivate Factory

activate ShowProposalRepo

ShowProposalRepo -> ShowProposalRepo : findAllTestingProposalsByShowRequest(showRequest)
activate ShowProposalRepo

ShowProposalRepo -> Controller : proposals

deactivate ShowProposalRepo

deactivate ShowProposalRepo

Controller -> UI : proposals

deactivate Controller
UI -> User : asks to select a proposal

User -> UI : selects a proposal

UI -> Controller : listVideos()
activate Controller

Controller -> List : getVideos()

activate List

List -> List : getVideos()

List -> Controller : videos

deactivate List

Controller -> UI : videos

deactivate Controller

UI -> User : asks to select a video

User -> UI : selects a video

UI -> Controller : addVideoToProposal(video, proposal)

activate Controller

Controller -> Proposal: addVideo(video)

activate Proposal

Proposal -> Proposal : addVideo(video)
Proposal -> Controller : video added
deactivate Proposal

Controller -> Persistence : PersistenceContext()

activate Persistence

Persistence -> Factory : repositories()

deactivate Persistence
activate Factory

Factory -> ShowProposalRepo : proposals()
deactivate Factory
activate ShowProposalRepo

ShowProposalRepo -> ShowProposalRepo : save(proposal)
activate ShowProposalRepo

ShowProposalRepo -> Controller : proposal saved
deactivate ShowProposalRepo

deactivate ShowProposalRepo

Controller -> UI : video added to proposal

deactivate Controller
UI -> User : video added to proposal

deactivate UI
deactivate User

@enduml