@startuml
set separator none
left to right direction


package "Domain" #DDDDDD {

    package "Repository " #DDDDDD {
        Interface ShowProposalRepository <<Repository>> {

        }

        Interface RepositoryFactory <<Factory>> {
            - RepositoryFactory()
            + proposals() : ShowProposalRepository
            + crmCollaborators() : CRMCollaboratorRepository
            + showRequests() : ShowRequestRepository
            + customers() : CustomerRepository
        }

        Interface ShowRequestRepository <<Repository>> {
            + findAllCreatedShowRequestsByCustomer(customer) : ShowRequest
        }

        Interface CRMCollaboratorRepository <<Repository>> {
            + findCollaboratorByEmail(email) : CRMCollaborator
        }

        Interface CustomerRepository <<Repository>> {
            + findAllCreatedCustomers() : Iterable<Customer>
        }

    }
    enum ShowProposalStatus <<Value Object>>{
    }

    class ShowProposal <<Entity>> <<root>>{
    }

    class ShowRequest <<Entity>> <<root>>{
    }

    class CRMCollaborator <<Entity>> <<root>>{
    }

    class Date <<Value Object>>{
    }

    class QuantityOfDrones <<Value Object>>{
    }

    class Time <<Value Object>>{
    }

    class Insurance <<Value Object>>{
    }

    class Customer <<Entity>> <<root>>{
    }

    class ShowProposalNumber <<Value Object>>{
    }

}

package "UI" #DDDDDD {
    class CreateShowProposalUI <<UI>> {

    }
}

package "Controller" #DDDDDD {
    class CreateShowProposalController <<Controller>> {
        + createShowProposal(showRequest, quant_drones, insurance, collaborator, date, time) : ShowProposal
        + listCustomers()
        + listShowRequests()
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaCustomerRepository <<Repository>> {
        + findAllCreatedCustomers() : Iterable<Customer>
    }

    class JpaRepositoryFactory <<Factory>> {
        - JpaRepositoryFactory()
        + proposals() : ShowProposalRepository
        + crmCollaborators() : CRMCollaboratorRepository
        + showRequests() : ShowRequestRepository
        + customers() : CustomerRepository

    }

    class JpaShowRequestRepository <<Repository>> {
        + findAllCreatedShowRequestsByCustomer(customer) : ShowRequest
    }

    class JpaCRMCollaboratorRepository <<Repository>> {
        + findCollaboratorByEmail(email) : CRMCollaborator
    }

    class JpaShowProposalRepository <<Repository>> {

    }


}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryCustomerRepository <<Repository>> {
        + findAllCreatedCustomers() : Iterable<Customer>
    }

    class InMemoryRepositoryFactory <<Factory>> {
        - InMemoryRepositoryFactory()
        + proposals() : ShowProposalRepository
        + crmCollaborators() : CRMCollaboratorRepository
        + showRequests() : ShowRequestRepository
        + customers() : CustomerRepository
    }

    class InMemoryShowRequestRepository <<Repository>> {
        + findAllCreatedShowRequestsByCustomer(customer) : ShowRequest
    }
    class InMemoryCRMCollaboratorRepository <<Repository>> {
        + findCollaboratorByEmail(email) : CRMCollaborator
    }
    class InMemoryShowProposalRepository <<Repository>> {

    }
}

package "persistence" #DDDDDD {
    class PersistenceContext {
        repositories() : RepositoryFactory
    }
}

' Relações entre as classes

'ShowProposal -> x

ShowProposal --> "1" CRMCollaborator: created by
ShowProposal --> "1" ShowRequest: based on
ShowProposal --> "1" ShowProposalStatus: proposalStatus
ShowProposal --> "1" QuantityOfDrones: qnt_drones
ShowProposal --> "1" Time: time
ShowProposal --> "1" Date: date
ShowProposal --> "1" Insurance: insurance
ShowProposal --> "1" ShowProposalNumber: proposalNumber

ShowRequest --> "1" Customer: requested by

RepositoryFactory ..> ShowProposalRepository : proposals()
RepositoryFactory ..> ShowRequestRepository : showRequests()
RepositoryFactory ..> CRMCollaboratorRepository : crmCollaborators()
RepositoryFactory ..> CustomerRepository : customers()

ShowProposalRepository --> "0..*" ShowProposal : proposals
ShowRequestRepository --> "0..*" ShowRequest : showRequests
CRMCollaboratorRepository --> "0..*" CRMCollaborator : crmCollaborators
CustomerRepository --> "0..*" Customer : customers

CreateShowProposalUI ..> CreateShowProposalController
CreateShowProposalController ..> RepositoryFactory : proposals()
CreateShowProposalController ..> RepositoryFactory : crmCollaborators()
CreateShowProposalController ..> RepositoryFactory : showRequests()
CreateShowProposalController ..> RepositoryFactory : customers()

CreateShowProposalController ..> ShowRequestRepository : findAllCreatedShowRequestsByCustomer(customer)
CreateShowProposalController ..> CustomerRepository : findAllCreatedCustomers()
CreateShowProposalController ..> CRMCollaboratorRepository : findCollaboratorByEmail(email)

CreateShowProposalController ..> PersistenceContext : repositories()


PersistenceContext ..> JpaRepositoryFactory : JpaRepositoryFactory()
PersistenceContext ..> InMemoryRepositoryFactory : InMemoryRepositoryFactory()
PersistenceContext ..> RepositoryFactory : proposals()
PersistenceContext ..> RepositoryFactory : crmCollaborators()
PersistenceContext ..> RepositoryFactory : showRequests()
PersistenceContext ..> RepositoryFactory : customers()

PersistenceContext ..> JpaShowRequestRepository : JpaShowRequestRepository()
PersistenceContext ..> InMemoryShowRequestRepository : InMemoryShowRequestRepository()
PersistenceContext ..> JpaCRMCollaboratorRepository : JpaCRMCollaboratorRepository()
PersistenceContext ..> InMemoryCRMCollaboratorRepository : InMemoryCRMCollaboratorRepository()
PersistenceContext ..> JpaShowProposalRepository : JpaShowProposalRepository()
PersistenceContext ..> InMemoryShowProposalRepository : InMemoryShowProposalRepository()
PersistenceContext ..> JpaCustomerRepository : JpaCustomerRepository()
PersistenceContext ..> InMemoryCustomerRepository : InMemoryCustomerRepository()

JpaRepositoryFactory ...|> RepositoryFactory : proposals()


JpaRepositoryFactory ..> JpaShowRequestRepository
JpaRepositoryFactory ..> JpaCustomerRepository
JpaRepositoryFactory ..> JpaCRMCollaboratorRepository
JpaRepositoryFactory ..> JpaShowProposalRepository

JpaShowRequestRepository ..|> ShowRequestRepository : findAllCreatedShowRequestsByCustomer(customer)
JpaCustomerRepository ..|> CustomerRepository : findAllCreatedCustomers()
JpaCRMCollaboratorRepository ..|> CRMCollaboratorRepository : findCollaboratorByEmail(email)
JpaShowProposalRepository ..|> ShowProposalRepository : save(showProposal)

InMemoryRepositoryFactory ..> InMemoryCustomerRepository
InMemoryRepositoryFactory ..> InMemoryShowRequestRepository
InMemoryRepositoryFactory ..> InMemoryCRMCollaboratorRepository
InMemoryRepositoryFactory ..> InMemoryShowProposalRepository

InMemoryCustomerRepository ..|> CustomerRepository : findAllCreatedCustomers()
InMemoryShowRequestRepository ..|> ShowRequestRepository : findAllCreatedShowRequestsByCustomer(customer)
InMemoryCRMCollaboratorRepository ..|> CRMCollaboratorRepository : findCollaboratorByEmail(email)
InMemoryShowProposalRepository ..|> ShowProposalRepository : save(showProposal)
@enduml