@startuml

enum ShowProposalStatus <<Value Object>>{
}

class ShowProposal <<Entity>> <<root>>{
}

class ShowProposalTemplate <<Value Object>>{
}

class ShowRequest <<Entity>> <<root>>{
}

class CRMCollaborator <<Entity>> <<root>>{
}

class Figure <<Entity>> <<root>>{
}

class Date <<Value Object>>{
}

class QuantityOfDrones <<Value Object>>{
}

class Time <<Value Object>>{
}

class Model <<Entity>> <<root>>{
}

class Insurance <<Value Object>>{
}

class FeedbackEmail <<Value Object>>{
}

    'ShowProposal -> x
    ShowProposal --> "1" FeedbackEmail: feedbackEmail
    ShowProposal --> "1" CRMCollaborator: created by
    ShowProposal --> "1" ShowRequest: based on
    ShowProposal --> "1" ShowProposalStatus: proposalStatus
    ShowProposal --> "0..*" Figure : requests new
    ShowProposal --> "1" ShowProposalTemplate: template
    ShowProposal --> "1..*" Model: uses
    ShowProposal ----> "1" QuantityOfDrones: qnt_drones
    ShowProposal ----> "1" Time: time
    ShowProposal ----> "1" Date: date
    ShowProposal --> "1" Insurance: insurance


@enduml