@startuml

package "Authentication" <<aggregate>> {

    class User <<Entity>> <<root>> {
        +userId: String
        +email: String
        +password: String
        +authenticate(): Boolean
    }

    class AuthenticationToken <<Value Object>> {
        +token: String
        +expiryDate: Date
    }

    ' User pode gerar o AuthenticationToken mas ele será tratado separadamente
    User --> "0..*" AuthenticationToken : generates
}

package "Authorization" <<aggregate>> {

    class UserRole <<Entity>> <<root>> {
        +roleName: String
    }

    class Permission <<Value Object>> {
        +permissionName: String
    }

    ' UserRole pode ter múltiplas permissões
    UserRole --> "0..*" Permission : grants
}

@enduml
