@startuml
'https://plantuml.com/sequence-diagram


 class Model <<Entity>> <<root>>{
    }

    class ModelID <<Value Object>>{
    }

    class WindTolerance <<Value Object>>{
    }

    class WindSpeed <<Value Object>>{
    }

    class PositionTolerance <<Value Object>>{
    }

    enum SafetyStatus <<Value Object>>{
    }

    'Model -> x
    Model --> "1" ModelID: id
    Model --> "1" WindTolerance: windTolerance
    Model --> "1" WindSpeed: windSpeed
    Model --> "1" PositionTolerance: positionTolerance
    Model --> "1" SafetyStatus: safetyStatus

@enduml