@startuml
'https://plantuml.com/sequence-diagram



    class Model <<Entity>> <<root>>{
    }

    class Configuration <<Entity>>{
    }

    class WindSpeed <<Value Object>>{
    }

    class PositionTolerance <<Value Object>>{
    }

    enum SafetyStatus <<Value Object>>{
    }

    'Model -> x
    Model --> "1" Configuration: configuration
    Configuration --> "1..*" WindSpeed: windSpeed
    Configuration --> "1..*" PositionTolerance: positionTolerance
    Model --> "1" SafetyStatus: safetyStatus
        SafetyStatus -->  Configuration: depends


@enduml