@startuml
'https://plantuml.com/sequence-diagram


  class Drone <<Entity>> <<root>>{
      }

      class SerialNumber <<Value Object>>{
      }

      enum DroneStatus <<Value Object>>{
      }

       class RemovalReason <<Value Object>>{
          }

      'Drone -> x
      Drone --> "1" DroneStatus: status
      Drone --> "1" SerialNumber: serialNumber
      Drone --> "0..*" RemovalReason: removalReason

@enduml