@startuml
'skinparam monochrome

skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "DroneTech" as DT
participant ":RemoveDronelUI" as UI
participant ":RemoveDroneController" as CTRL
participant ":Persistence" as PERS
participant ":RepositoryFactory" as REPOS
participant ":repositoryFactory\n::RepositoryFactory" as REPOS_SINGLETON
participant "droneRepository\n:DroneRepository" as DRN_REPO
participant "drone\n:Drone" as DRN

activate DT

DT -> UI : requests to remove a drone in the inventory
activate UI
    UI --> DT : asks for drone serial number and the reason for removal
    deactivate UI
    DT -> UI : submits data
    activate UI
    UI --> UI : keepData(serialNumber, removReason)
    UI --> DT : asks for confirmation
    deactivate UI
    DT -> UI : confirms data
    activate UI
    UI -> CTRL : removeDrone(serialNumber, removReason)
    activate CTRL
        CTRL -> CTRL :getDroneRepository()
        activate CTRL
        CTRL -> PERS : getRepositoryFactory
                                    activate PERS
                                    PERS --> CTRL : repositoryFactory
                                    deactivate PERS
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getDroneRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : droneRepository
        deactivate REPOS_SINGLETON
        CTRL --> CTRL : droneRepository

        deactivate CTRL
            CTRL -> DRN_REPO : removeDrone(serialNumber, removReason)
            activate DRN_REPO


                    DRN_REPO -> DRN_REPO: validateRemoval(serialNumber)
                    activate DRN_REPO
                        DRN_REPO --> DRN_REPO : true
                    deactivate DRN_REPO

        DRN_REPO -> DRN_REPO : addDrnRemovData(serialNumber, \nremovReason)
        DRN_REPO -> DRN** : changeDrnStatRemv(serialNumber)
                    DRN_REPO --> CTRL : true

        deactivate DRN_REPO

        CTRL --> UI : true

    deactivate CTRL

UI --> DT : displays success message
deactivate UI
deactivate DT

@enduml
