@startuml
set separator none

package "Domain" #DDDDDD {

    package "Repository " #DDDDDD {
        Interface CustomerRepository <<Repository>> {
            + getCustomers() : List<Customer>
        }

        Interface RepositoryFactory <<Factory>> {
            - RepositoryFactory()
            + getCustomerRepository() : CustomerRepository
        }

    }

    class Customer <<Entity>> {
        + Customer (name, address, vat, status, type)
        + addRepresentative (representative)
    }
    class CustomerRepresentative <<Entity>> {
        + CustomerRepresentative (name, position, email, phoneNumber)
        + setCustomer (customer)
    }

    class Address <<Value Object>> {

    }
    class VatNumber <<Value Object>> {

    }
    enum CustomerStatus <<Value Object>> {

    }
    enum CustomerType <<Value Object>> {

    }
    class Position <<Value Object>> {

    }
    class Name <<Value Object>> {

    }
    class Email <<Value Object>> {

    }
    class PhoneNumber <<Value Object>> {

    }

    enum CustomerRepresentativeStatus <<Value Object>>{
    }
}

package "UI" #DDDDDD {
    class AddCustomerRepresentativeUI <<UI>> {

    }
}

package "Controller" #DDDDDD {
    class AddCustomerRepresentativeController <<Controller>> {
        + registerNewRepresentativeOfCustomer(customer, representative)
        + listAllCustomers()
    }
}

package "persistence.impl.jpa" #DDDDDD {
    class JpaCustomerRepository <<Repository>> {
    }

    class JpaRepositoryFactory <<Factory>> {
        - JpaRepositoryFactory()
    }

}

package "persistence.impl.inmemory" #DDDDDD {
    class InMemoryCustomerRepository <<Repository>> {
    }

    class InMemoryRepositoryFactory <<Factory>> {
        - InMemoryRepositoryFactory()
    }
}

package "persistence" #DDDDDD {
    class PersistenceContext {
        getRepositoryFactory() : RepositoryFactory
    }
}

' Relações entre as classes
Customer --> "1..*" CustomerRepresentative : representatives
Customer --> "1" VatNumber : vat
Customer --> "1" Address : address
Customer --> "1" CustomerStatus : status
Customer --> "1" CustomerType : type
Customer ----> "1" Name : name

CustomerRepresentative --> "1" Position : position
CustomerRepresentative --> "1" Name : name
CustomerRepresentative --> "1" Email : email
CustomerRepresentative --> "1" PhoneNumber : phoneNumber
CustomerRepresentative --> "1" CustomerRepresentativeStatus : status


RepositoryFactory ..> CustomerRepository : getCustomers()

CustomerRepository --> "0..*" Customer : customers

AddCustomerRepresentativeUI ..> AddCustomerRepresentativeController
AddCustomerRepresentativeController ..> RepositoryFactory : getFigureRepository()
AddCustomerRepresentativeController ..> CustomerRepository : getCustomers()
AddCustomerRepresentativeController ..> PersistenceContext : getRepositoryFactory()


PersistenceContext ..> JpaRepositoryFactory : JpaRepositoryFactory()
PersistenceContext ..> InMemoryRepositoryFactory : InMemoryRepositoryFactory()
PersistenceContext ..> RepositoryFactory : getCustomerRepository()

JpaRepositoryFactory ...|> RepositoryFactory : getCustomerRepository()
JpaRepositoryFactory ..> JpaCustomerRepository

JpaCustomerRepository ..|> CustomerRepository : getCustomers()

InMemoryRepositoryFactory .|> RepositoryFactory : getCustomerRepository()
InMemoryRepositoryFactory ..> InMemoryCustomerRepository

InMemoryCustomerRepository ..|> CustomerRepository : getCustomers()

@enduml